/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univates;

/**
 *
 * @author leonardo.souza1
 */
public class telaPrincipal extends javax.swing.JFrame {
        Pessoa pessoa1;
        Pessoa pessoa2;
    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        pessoa1 = new Pessoa();
        pessoa2 = new Pessoa();
        
        pessoa1.setCodigo(1);
        pessoa1.setNome("joão");
        pessoa1.setEndereco("Lajeado");
        pessoa1.setTelefone("190");
        pessoa1.setValorConta(500);
        pessoa1.setChequeEspecial(200);

        pessoa2.setCodigo(2);
        pessoa2.setNome("Mario");
        pessoa2.setEndereco("Taquari");
        pessoa2.setTelefone("181");
        pessoa2.setValorConta(1000);
        pessoa2.setChequeEspecial(100);
        
        //String.valueOf()  = converte qualquer valor para string
        lblNome1.setText(pessoa1.getNome());
        lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
        lblChequeEspecial1.setText((String.valueOf(pessoa1.getChequeEspecial())));
        
        lblNome2.setText(pessoa2.getNome());
        lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
        lblChequeEspecial2.setText((String.valueOf(pessoa2.getChequeEspecial())));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome1 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblChequeEspecial1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblChequeEspecial2 = new javax.swing.JLabel();
        btnTranf1 = new javax.swing.JButton();
        btnTranf2 = new javax.swing.JButton();
        txtValorTranf2 = new javax.swing.JTextField();
        txtValorTranf1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome1.setText("jLabel1");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblValor1.setText("jLabel1");
        getContentPane().add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblChequeEspecial1.setText("jLabel1");
        getContentPane().add(lblChequeEspecial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblNome2.setText("jLabel1");
        getContentPane().add(lblNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lblValor2.setText("jLabel1");
        getContentPane().add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        lblChequeEspecial2.setText("jLabel1");
        getContentPane().add(lblChequeEspecial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        btnTranf1.setText("Tranferencia");
        btnTranf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranf1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTranf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        btnTranf2.setText("Tranferencia");
        btnTranf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranf2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTranf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));
        getContentPane().add(txtValorTranf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 90, -1));
        getContentPane().add(txtValorTranf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 90, -1));

        setSize(new java.awt.Dimension(267, 187));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTranf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranf1ActionPerformed
        // TODO add your handling code here:
         try{
            double transf = Double.parseDouble(txtValorTranf1.getText());
            if(pessoa1.credito(transf) == true){
                pessoa2.debito(transf);
            }
            lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
            lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
            txtValorTranf1.setText("0");
        
        }catch(Exception ex){
            System.out.println("Erro: " + ex.getMessage());
        }
   
    }//GEN-LAST:event_btnTranf1ActionPerformed

    private void btnTranf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranf2ActionPerformed
        // TODO add your handling code here:
         try{
        double tranf = Double.parseDouble(txtValorTranf2.getText());
        if(pessoa2.credito(tranf) == true){
            pessoa1.debito(tranf);
        }
        lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
        lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
        txtValorTranf2.setText("0");
        
        }catch (Exception e){
                System.out.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTranf2ActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTranf1;
    private javax.swing.JButton btnTranf2;
    private javax.swing.JLabel lblChequeEspecial1;
    private javax.swing.JLabel lblChequeEspecial2;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JTextField txtValorTranf1;
    private javax.swing.JTextField txtValorTranf2;
    // End of variables declaration//GEN-END:variables
}
